name: "Repository set labels sync"
description: "Aggregates and syncs labels across a set of repositories."

inputs:
  data-directory:
    description: "Where to store labels for repositories"
    required: true
    default: "path/to/data"
  repositories-filename:
    description: "Filename of existing repositories JSON list."
    required: true
    default: "path/to/json"
  labels-filename:
    description: "Filename to save labels data."
    required: true
    default: "path/to/json"
  token:
    description: "Token to use to authenticate repositories."
    required: true
    default: ""
runs:
  using: 'node12'
  main: 'dist/index.js'